### ISSUE TITLE
CI Failing in build model step

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#1112]
Below is the last portion of the stack trace:

```
Traceback (most recent call last):
  File "/__w/spdx-spec/spdx-spec/spec-parser/main.py", line 13, in <module>
    m.gen_all(cfg.output_dir, cfg)
  File "/__w/spdx-spec/spdx-spec/spec-parser/spec_parser/model.py", line 1[80](https://github.com/spdx/spdx-spec/actions/runs/10742933601/job/29796597747#step:8:81), in gen_all
    gen_tex(self, outdir, cfg)
  File "/__w/spdx-spec/spdx-spec/spec-parser/spec_parser/tex.py", line 33, in gen_tex
    page = template.render(vars(ns))
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/__w/spdx-spec/spdx-spec/spec-parser/spec_parser/templates/tex/namespace.tex.j2", line 9, in top-level template code
    {{markdown_to_tex(description)}}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/__w/spdx-spec/spdx-spec/spec-parser/spec_parser/tex.py", line 130, in markdown_to_tex
    process = subprocess.run(
              ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1[95](https://github.com/spdx/spdx-spec/actions/runs/10742933601/job/29796597747#step:8:96)5, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pandoc'
```

**Comment by zvr** [comment]
It's not really needed for anything related to the CI, since it's only the for the TeX output.

I can add an option to `spec-parser` to only invoke it when specified in command-line, or you can simply have a "pandoc" executable script that does nothing.

**Comment by bact** [comment]
Should be fixed by #1113

**Comment by bact** [comment]
> I can add an option to `spec-parser` to only invoke it when specified in command-line, or you can simply have a "pandoc" executable script that does nothing. `(echo /bin/sh; echo exit 0) > pandoc ; chmod +x pandoc`

I really like the idea. It will save running time as well.

Have tried to created the "pandoc" script as suggested but still to figure out the path that Python will looking for it. Once figured out, I can replace the actual installation of pandoc with this "pandoc" script. But for the meantime, #1113 can do the job.
