### ISSUE TITLE
Validation script consistently showing errors

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#583]
The validate check is failing while running mkdocs:

```
Run mkdocs build -v --clean
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 5, in <module>
    from mkdocs.__main__ import cli
  File "/usr/local/lib/python3.10/site-packages/mkdocs/__main__.py", line 16, in <module>
    from mkdocs import config                                 # noqa: E402
  File "/usr/local/lib/python3.10/site-packages/mkdocs/config/__init__.py", line 2, in <module>
    from mkdocs.config.defaults import DEFAULT_SCHEMA
  File "/usr/local/lib/python3.10/site-packages/mkdocs/config/defaults.py", line 1, in <module>
    from mkdocs.config import config_options
  File "/usr/local/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 2, in <module>
    from collections import Sequence, namedtuple
ImportError: cannot import name 'Sequence' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
Error: Process completed with exit code 1.
```

This now fails for any new PR's.  I re-ran the validation for a previously successful validation (PR #579) and it now fails where it succeeded when the script was first run.

I am able to successfully run this on my local copy of the repo.

**Comment by kestewart** [comment]
@goneall - I'm going to close this, as I think its all been resolved with the merges.   Please reopen if this isn't the case.
