### ISSUE TITLE
CI Build Failing

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#756]
The CI is failing on the v3-draft and v2-draft branches with the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line [5](https://github.com/spdx/spdx-spec/runs/7449013575?check_suite_focus=true#step:5:6), in <module>
    from mkdocs.__main__ import cli
  File "/usr/local/lib/python3.10/site-packages/mkdocs/__main__.py", line 1[6](https://github.com/spdx/spdx-spec/runs/7449013575?check_suite_focus=true#step:5:7), in <module>
    from mkdocs import config                                 # noqa: E402
  File "/usr/local/lib/python3.[10](https://github.com/spdx/spdx-spec/runs/7449013575?check_suite_focus=true#step:5:11)/site-packages/mkdocs/config/__init__.py", line 2, in <module>
    from mkdocs.config.defaults import DEFAULT_SCHEMA
  File "/usr/local/lib/python3.10/site-packages/mkdocs/config/defaults.py", line 1, in <module>
    from mkdocs.config import config_options
  File "/usr/local/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 2, in <module>
    from collections import Sequence, namedtuple
ImportError: cannot import name 'Sequence' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
Error: Process completed with exit code 1.
```

**Comment by kestewart** [comment]
@goneall, @iamwillbar - is this resolved now, or is there still work to do.   If it's good, could one of you please close this.

**Comment by goneall** [comment]
Creating a new issue to track the fact that https://spdx.github.io/spdx-spec/ points to 2.2.2 instead of 2.3
