### ISSUE TITLE
CI failing installing pre-requisites for 2.3.1 builds

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#896]
Following is the error:

```
Run pip install -r requirements.txt
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Collecting mkdocs==1.3.0 (from -r requirements.txt (line 1))
  Downloading mkdocs-1.3.0-py3-none-any.whl.metadata ([4](https://github.com/spdx/spdx-spec/actions/runs/8557678006/job/23450504426#step:4:5).8 kB)
Collecting json-schema-for-humans==0.39.5 (from -r requirements.txt (line 2))
  Downloading json_schema_for_humans-0.39.5-py3-none-any.whl.metadata (10 kB)
Collecting click>=3.3 (from mkdocs==1.3.0->-r requirements.txt (line 1))
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting Jinja2>=2.10.2 (from mkdocs==1.3.0->-r requirements.txt (line 1))
  Downloading Jinja2-3.1.3-py3-none-any.whl.metadata (3.3 kB)
Collecting Markdown>=3.2.1 (from mkdocs==1.3.0->-r requirements.txt (line 1))
  Downloading Markdown-3.6-py3-none-any.whl.metadata (7.0 kB)
Collecting PyYAML>=3.10 (from mkdocs==1.3.0->-r requirements.txt (line 1))
  Downloading PyYAML-6.0.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting watchdog>=2.0 (from mkdocs==1.3.0->-r requirements.txt (line 1))
  Downloading watchdog-4.0.0-py3-none-manylinux2014_x86_64.whl.metadata (37 kB)
Collecting ghp-import>=1.0 (from mkdocs==1.3.0->-r requirements.txt (line 1))
  Downloading ghp_import-2.1.0-py3-none-any.whl.metadata (7.2 kB)
Collecting pyyaml-env-tag>=0.1 (from mkdocs==1.3.0->-r requirements.txt (line 1))
  Downloading pyyaml_env_tag-0.1-py3-none-any.whl.metadata (4.1 kB)
Collecting importlib-metadata>=4.3 (from mkdocs==1.3.0->-r requirements.txt (line 1))
  Downloading importlib_metadata-7.1.0-py3-none-any.whl.metadata (4.7 kB)
Collecting packaging>=20.[5](https://github.com/spdx/spdx-spec/actions/runs/8557678006/job/23450504426#step:4:6) (from mkdocs==1.3.0->-r requirements.txt (line 1))
  Downloading packaging-24.0-py3-none-any.whl.metadata (3.2 kB)
Collecting mergedeep>=1.3.4 (from mkdocs==1.3.0->-r requirements.txt (line 1))
  Downloading mergedeep-1.3.4-py3-none-any.whl.metadata (4.3 kB)
Collecting PyYAML>=3.10 (from mkdocs==1.3.0->-r requirements.txt (line 1))
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 30.5 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-lmwszkmk/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-lmwszkmk/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-lmwszkmk/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-lmwszkmk/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-lmwszkmk/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-lmwszkmk/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-lmwszkmk/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 9[6](https://github.com/spdx/spdx-spec/actions/runs/8557678006/job/23450504426#step:4:7)9, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-lmwszkmk/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 96[7](https://github.com/spdx/spdx-spec/actions/runs/8557678006/job/23450504426#step:4:8), in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-lmwszkmk/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 9[8](https://github.com/spdx/spdx-spec/actions/runs/8557678006/job/23450504426#step:4:9)8, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-lmwszkmk/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/tmp/pip-build-env-lmwszkmk/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 32[9](https://github.com/spdx/spdx-spec/actions/runs/8557678006/job/23450504426#step:4:10), in find_sources
          mm.run()
        File "/tmp/pip-build-env-lmwszkmk/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 550, in run
          self.add_defaults()
        File "/tmp/pip-build-env-lmwszkmk/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-lmwszkmk/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line [10](https://github.com/spdx/spdx-spec/actions/runs/8557678006/job/23450504426#step:4:11)2, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-lmwszkmk/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-lmwszkmk/overlay/lib/python3.[12](https://github.com/spdx/spdx-spec/actions/runs/8557678006/job/23450504426#step:4:13)/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-lmwszkmk/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by goneall** [comment]
@licquia - any ideas?

**Comment by goneall** [comment]
Duplicate of #867
